### ISSUE TITLE
Make use of improvements in Distributions.jl v0.17.0

### ISSUE THREAD

**Issue by lassepe** [JuliaPOMDP/POMDPModelTools.jl#13]
[Distributions.jl](https://github.com/JuliaStats/Distributions.jl) has made some progress towards using generic containers. This renders some functions / fixes provided in [`src/distributions`](https://github.com/JuliaPOMDP/POMDPModelTools.jl/tree/11e22a3c6d538d0e626860514f4d1ad3f13f1d80/src/distributions) obsolete.

**Comment by MaximeBouton** [comment]
is this file the only file affected? https://github.com/JuliaPOMDP/POMDPModelTools.jl/blob/master/src/distributions/distributions_jl.jl

We don't need the extra `rand` methods thanks to JuliaStats/Distributions.jl#830

**Comment by zsunberg** [comment]
@MaximeBouton yeah, I think that should be the only file.
