### ISSUE TITLE
Pretty printing of distributions with UnicodePlots.barplot

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPModelTools.jl#22]
This could be really useful for visually explaining how `transition` and `observation` are supposed to return a distribution. It would look like this:

![Screenshot from 2019-06-07 17-01-56](https://user-images.githubusercontent.com/4240491/59139159-200dc480-8946-11e9-934c-80d5afb2fc1e.png)

https://github.com/Evizero/UnicodePlots.jl#barplot

**Comment by zsunberg** [comment]
(we could get rid of the 0.0 entry)

**Comment by mykelk** [comment]
So pretty!!!
