### ISSUE TITLE
should info return missing by default?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPModelTools.jl#3]

**Comment by mykelk** [comment]
I don't think so. It's not missing. Probably nothing.

**Comment by zsunberg** [comment]
Missing makes more sense if you think of it as being in a history of things returned by a simulation.

**Comment by zsunberg** [comment]
When there is no observation available, it is represented by `missing`. Is info the same as that or fundamentally different?

**Comment by mykelk** [comment]
I was thinking it is different, but I'm okay either way.

**Comment by zsunberg** [comment]
Now I am leaning towards nothing.

Perhaps this is a useful way to think about the distinction:
- nothing is for things that do not exist
- missing is for things that exist, but we do not know/have access to at this time
