### ISSUE TITLE
Difficult-to-interpret error if SparseCat probs are not numbers

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPModelTools.jl#35]
```
d = SparseCat(["something"], Any[1]);
pdf(d, "something else")
```
Throws a `MethodError` for `zero`. It would be nice if it was more informative.

**Comment by zsunberg** [comment]
This can happen if, for instance, you do
```
probs = []
push!(probs, 1.0)
return SparseCat(stuff, probs)
```

**Comment by mykelk** [comment]
This confused some students and got them stuck for a while. Perhaps at construction of `SparseCat` just convert the probs into a `Vector{Float64}`?

**Comment by zsunberg** [comment]
Thanks for the suggestion! I tried to fix it fairly narrowly to maintain flexibility in what containers people could use.
